version: '3.7'
services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: reserva     
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    volumes: 
      - db-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports: 
      - "8081:80"
    links:
      - db:localhost
volumes:
  db-data:
  pgadmin-data: